#!/usr/bin/env python
"""Extract the narration from a video's scene files into a readable script.

    python tools/export_script.py navier_stokes   # -> videos/navier_stokes/SCRIPT.md

The narration lives in the scene code (``self.voiceover("...")``) so audio and
animation can never drift apart; this tool turns it back into a document for
proof-reading, fact-checking, or recording a human voiceover.

Narration computed from data (f-strings) can't be read from the source alone:
for those scenes the text actually spoken in the latest ``tools/build.py``
render (``media/<video>/videos/<module>/<quality>/<Scene>.narration.json``) is
used when one exists, and otherwise the f-string is shown with its
``{placeholders}``.
"""

from __future__ import annotations

import ast
import importlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

BOOKMARK = re.compile(r"<bookmark[^>]*/>")


def _voiceover_calls(path: Path) -> dict[str, list[tuple[int, str | None, bool]]]:
    """{class name: [(line number, narration text, computed?)]}.  A computed line keeps its ``{placeholders}``
    if it is an f-string; any other expression (a variable, say) has no text here (None)."""
    out: dict[str, list[tuple[int, str, bool]]] = {}
    for node in ast.walk(ast.parse(path.read_text())):
        if not isinstance(node, ast.ClassDef):
            continue
        for call in ast.walk(node):
            if (
                isinstance(call, ast.Call)
                and isinstance(call.func, ast.Attribute)
                and call.func.attr == "voiceover"
                and call.args
            ):
                try:
                    text, computed = ast.literal_eval(call.args[0]), False
                except ValueError:
                    computed = True
                    text = ast.unparse(call.args[0])[2:-1] if isinstance(call.args[0], ast.JoinedStr) else None
                if text is not None:
                    text = " ".join(BOOKMARK.sub("", text).split())
                out.setdefault(node.name, []).append((call.lineno, text, computed))
    return {k: sorted(v) for k, v in out.items()}


def narration_by_class(path: Path) -> dict[str, list[str]]:
    """{class name: its literal narration lines, in source order} (lines computed from data are left out)."""
    out = {k: [t for _, t, computed in v if not computed] for k, v in _voiceover_calls(path).items()}  # literals only
    return {k: v for k, v in out.items() if v}


def rendered_narration(video: str, module: str, cls: str) -> list[str] | None:
    """The narration as spoken in the most recent ``tools/build.py`` render of this scene, if any."""
    found = sorted((ROOT / "media" / video / "videos" / module).glob(f"*/{cls}.narration.json"), key=lambda f: f.stat().st_mtime)
    if not found:
        return None
    return [" ".join(BOOKMARK.sub("", line["text"]).split()) for line in json.loads(found[-1].read_text())["lines"]]


def script_lines(video: str, module: str, cls: str) -> list[str]:
    """A scene's narration: from the source, or from its latest render when some lines are computed from data."""
    calls = _voiceover_calls(ROOT / "videos" / video / f"{module}.py").get(cls, [])
    if any(computed for *_, computed in calls):
        return rendered_narration(video, module, cls) or [t for _, t, _ in calls if t is not None]
    return [t for _, t, _ in calls]


def main():
    video = sys.argv[1]
    manifest = importlib.import_module(f"videos.{video}.manifest")
    parts = [f"# {manifest.TITLE} — narration script\n", "_Generated by `tools/export_script.py` from the scene code. Do not edit by hand._\n"]
    words = 0
    for module, cls, chapter in manifest.SCENES:
        lines = script_lines(video, module, cls)
        parts.append(f"\n## {chapter or cls}\n\n_Scene `{module}.py::{cls}`_\n")
        for line in lines:
            parts.append(f"\n{line}\n")
            words += len(line.split())
    parts.append(f"\n---\n\n{words} words (~{words / 155:.0f} min at 155 wpm).\n")
    dst = ROOT / "videos" / video / "SCRIPT.md"
    dst.write_text("".join(parts))
    print(f"Wrote {dst.relative_to(ROOT)} ({words} words)")


if __name__ == "__main__":
    main()
