#!/usr/bin/env python
"""Extract the narration from a video's scene files into a readable script.

    python tools/export_script.py navier_stokes   # -> videos/navier_stokes/SCRIPT.md

The narration lives in the scene code (``self.voiceover("...")``) so audio and
animation can never drift apart; this tool turns it back into a document for
proof-reading, fact-checking, or recording a human voiceover.

Narration computed from data (f-strings) can't be read from the source alone:
for those scenes the text actually spoken in the latest ``tools/build.py``
render (``media/<video>/videos/<module>/<quality>/<Scene>.narration.json``) is
used when one exists, and otherwise the f-string is shown with its
``{placeholders}``.
"""

from __future__ import annotations

import ast
import importlib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

BOOKMARK = re.compile(r"<bookmark[^>]*/>")


def narration_by_class(path: Path) -> dict[str, tuple[list[str], bool]]:
    """{class name: (narration lines in source order, whether any line is computed at render time)}."""
    tree = ast.parse(path.read_text())
    out: dict[str, tuple[list[str], bool]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        lines, computed = [], False
        for call in ast.walk(node):
            if (
                isinstance(call, ast.Call)
                and isinstance(call.func, ast.Attribute)
                and call.func.attr == "voiceover"
                and call.args
            ):
                try:
                    text = ast.literal_eval(call.args[0])
                except ValueError:
                    computed = True
                    text = ast.unparse(call.args[0])  # an f-string: keep its {placeholders}
                    if text[:2] in ('f"', "f'"):
                        text = text[2:-1]
                lines.append((call.lineno, " ".join(BOOKMARK.sub("", text).split())))
        if lines:
            out[node.name] = ([t for _, t in sorted(lines)], computed)
    return out


def rendered_narration(video: str, module: str, cls: str) -> list[str] | None:
    """The narration as spoken in the most recent render of this scene, if any."""
    found = sorted((ROOT / "media" / video / "videos" / module).glob(f"*/{cls}.narration.json"), key=lambda f: f.stat().st_mtime)
    if not found:
        return None
    return [" ".join(BOOKMARK.sub("", line["text"]).split()) for line in json.loads(found[-1].read_text())["lines"]]


def main():
    video = sys.argv[1]
    manifest = importlib.import_module(f"videos.{video}.manifest")
    parts = [f"# {manifest.TITLE} — narration script\n", "_Generated by `tools/export_script.py` from the scene code. Do not edit by hand._\n"]
    words = 0
    for module, cls, chapter in manifest.SCENES:
        lines, computed = narration_by_class(ROOT / "videos" / video / f"{module}.py").get(cls, ([], False))
        if computed:
            lines = rendered_narration(video, module, cls) or lines
        parts.append(f"\n## {chapter or cls}\n\n_Scene `{module}.py::{cls}`_\n")
        for line in lines:
            parts.append(f"\n{line}\n")
            words += len(line.split())
    parts.append(f"\n---\n\n{words} words (~{words / 155:.0f} min at 155 wpm).\n")
    dst = ROOT / "videos" / video / "SCRIPT.md"
    dst.write_text("".join(parts))
    print(f"Wrote {dst.relative_to(ROOT)} ({words} words)")


if __name__ == "__main__":
    main()
