#!/usr/bin/env python
"""Extract the narration from a video's scene files into a readable script.

    python tools/export_script.py navier_stokes   # -> videos/navier_stokes/SCRIPT.md

The narration lives in the scene code (``self.voiceover("...")``) so audio and
animation can never drift apart; this tool turns it back into a document for
proof-reading, fact-checking, or recording a human voiceover.
"""

from __future__ import annotations

import ast
import importlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

BOOKMARK = re.compile(r"<bookmark[^>]*/>")


def narration_by_class(path: Path) -> dict[str, list[str]]:
    tree = ast.parse(path.read_text())
    out: dict[str, list[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        lines = []
        for call in ast.walk(node):
            if (
                isinstance(call, ast.Call)
                and isinstance(call.func, ast.Attribute)
                and call.func.attr == "voiceover"
                and call.args
            ):
                try:
                    text = ast.literal_eval(call.args[0])
                except ValueError:
                    continue
                lines.append((call.lineno, " ".join(BOOKMARK.sub("", text).split())))
        if lines:
            out[node.name] = [t for _, t in sorted(lines)]
    return out


def main():
    video = sys.argv[1]
    manifest = importlib.import_module(f"videos.{video}.manifest")
    parts = [f"# {manifest.TITLE} — narration script\n", "_Generated by `tools/export_script.py` from the scene code. Do not edit by hand._\n"]
    words = 0
    for module, cls, chapter in manifest.SCENES:
        lines = narration_by_class(ROOT / "videos" / video / f"{module}.py").get(cls, [])
        parts.append(f"\n## {chapter or cls}\n\n_Scene `{module}.py::{cls}`_\n")
        for line in lines:
            parts.append(f"\n{line}\n")
            words += len(line.split())
    parts.append(f"\n---\n\n{words} words (~{words / 155:.0f} min at 155 wpm).\n")
    dst = ROOT / "videos" / video / "SCRIPT.md"
    dst.write_text("".join(parts))
    print(f"Wrote {dst.relative_to(ROOT)} ({words} words)")


if __name__ == "__main__":
    main()
